### ISSUE TITLE
Add depth setting

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/resource-rest-bundle#15]
This will set the children depth to return in the JSON response.

**Comment by ElectricMaxxx** [comment]
I have added a depth information in SEO https://github.comtsymfony-cmf/seo-bundle/pull/288 maybe we can put that "calculation" into a common Utils class? i think that is the same depth for seo and for api clients, right?

**Comment by wouterj** [comment]
This is a completely other concept of depth. The JSON response contains the current node info + it's children. These children contain the current node info + their children. These child-children contain their node info and their children. Etc.

Returning all children makes generating and parsing the request slow. Returning no children (depth=0) makes responses useless for some applications. Returning depth=1 children means some applications have to make many rest calls.

So we should have a depth setting that controls the depth of the children

**Comment by ElectricMaxxx** [comment]
Ah you mean a max_rendering_depth? 
I would suggest a default Value in configuration and a query parameter to enpower the client to do the decision on its own.

**Comment by ElectricMaxxx** [comment]
... and something equal we have in for the Treerowser.
But i would also suggest to server links to the next line of childs, when the max depth is reached, to give the client the oportunity to go deeper.
