### ISSUE TITLE
Add a depth request parameter

### ISSUE THREAD

**Issue by wouterj** [symfony-cmf/resource-rest-bundle#16]
We should be able to, besides configuring a global depth, change the depth per URL. This would allow the tree to immediately load the selected node, instead of using 3 requests to select the `/cmf/content/home` node.

**Comment by ElectricMaxxx** [comment]
I do not really understand what you meaan. Reading the code i would say there is a path parameter next to `/ap/[repo]/` and both repositories use this one to get the resource, or?
