### ISSUE TITLE
jms/serializer-bundle 1.0.0 version support 

### ISSUE THREAD

**Issue by gnorby88** [symfony-cmf/resource-rest-bundle#21]
When i install SonataDoctrinePhpcrAdminBundle, i received the following problem:
- Can only install one of: jms/serializer-bundle[1.0.0, 0.13.0].
- symfony-cmf/resource-rest-bundle 1.0.x-dev requires jms/serializer-bundle ~0.13
  But my other bundles require 1.0.0 version. Please just add the support for this version as well to composer (~0.13|~1.0).

**Comment by dantleech** [comment]
I think it makes sense to only support 1.0. Opened pull request #22

**Comment by dantleech** [comment]
The pull request was merged. Thanks for the report :)
