### ISSUE TITLE
Switch to Puli 1.0.x (dev-master is behind and there are conflicts)

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/resource-rest-bundle#28]
Caused by the curent state of Puli (1.0.0-beta6 - 1.0.0-beta10 isn't merged into master) we do have a newer commit in this bundle (1.0.0-beta10) then in the component (dev-master). They did some changes that breaks this bundle now. The reason is a change on the Repository Interface, that should force us to implement (getVersions()).

**Comment by dantleech** [comment]
So the `1.0` branch is ahead of `dev-master`. We should switch to the `1.0` branch.

**Comment by dantleech** [comment]
Done I think.

**Comment by dantleech** [comment]
Oh no, wrong repository.
