### ISSUE TITLE
Temprorary require symfony/translation

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/resource-rest-bundle#53]
To avoid installation issues based by a missing dependency in `jms/serializer-bundle` we should require `symfony/translation` temporary. JMS will release a fix on master, when Symfony 4.0 will be released. 

Created #54  to remove it.

**Comment by dbu** [comment]
can you please link to the jms issue about this for reference?

**Comment by ElectricMaxxx** [comment]
Here ist the issue: https://github.com/schmittjoh/JMSSerializerBundle/issues/606
and here is our build: https://travis-ci.org/symfony-cmf/install-testing/jobs/282267445  where it fails

**Comment by ElectricMaxxx** [comment]
But i really have problems to find a version to install each composer require fails. :-(

**Comment by ElectricMaxxx** [comment]
Now it got it. I think `sonata-admin` was to much on `require-dev`

**Comment by ElectricMaxxx** [comment]
@dbu shall we keep it on master until 2.1 or release a patch 2.0.1 ?
i prefer last one.

**Comment by ElectricMaxxx** [comment]
@dbu had a question here :-)

**Comment by dbu** [comment]
this bundle is at 1.x

i just created a signed release for 1.0.1 with this and the jms serializer fix.

**Comment by ElectricMaxxx** [comment]
thx.
